### ISSUE TITLE
FFmpeg, when called on a non-video file raises an error

### ISSUE THREAD

**Issue by jcoyne** [samvera/hydra-file_characterization#16]
I run this command:

``` ruby
      Hydra::FileCharacterization.characterize(f, [:fits, :ffprobe])
```

This error is raised:

```
 RuntimeError:
       Unable to execute command "ffprobe -i "/Users/justin/workspace/bawstun/spec/storage/qj/72/pc/13/m/broadway_or_bust.pbcore.xml" -print_format xml -show_streams -v quiet"
```

It seems like there should be some conditions for which this characterizer is run.

Interestingly ffmpeg is still returning valid output:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<ffprobe>
</ffprobe>
```

but it does warn that: "Invalid data found when processing input"

Perhaps characterizers need to be able to configure whether exit status must be success:
https://github.com/projecthydra/hydra-file_characterization/blob/c5b298f6cbbeac3a708badb43e355e0db40efe7a/lib/hydra/file_characterization/characterizer.rb#L45

**Comment by jrgriffiniii** [comment]
This is greater than 10 years in age, closing.
